<?php

namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use \PDF;
use App\Models\Contract;
use Illuminate\Support\Str;
use Symfony\Component\Process\Process;


class ContractController extends Controller
{
    public function generate_contract(Request $request){
        $data = $request->all();

        // $owner_sign = base64_decode($data['owner_signature']);
        // $owner_sign_filename = Str::random(32).'.png';
        // $owner_sign_path = storage_path('app/images/owner_signatures/'.$owner_sign_filename);
        // file_put_contents($owner_sign_path, $owner_sign);
        
        // $contractor_sign = base64_decode($data['contractor_signature']);
        // $contractor_sign_filename = Str::random(32).'.png';
        // $contractor_sign_path = storage_path('app/images/contractor_signatures/'.$contractor_sign_filename);
        // file_put_contents($contractor_sign_path, $contractor_sign);
        
        // $data['owner_signature']=$owner_sign_filename;
        // $data['contractor_signature']=$contractor_sign_filename;
        
        
        $pdf = PDF::loadView('contract_template', compact('data'));
        $pdf->setOptions(['dpi' => 150, 'defaultFont' => 'Arial']);
        $pdfContent = $pdf->output();
        $filename = Str::random(32).'.pdf';
        $filePath = storage_path('app/images/contracts/' . $filename);
        file_put_contents($filePath, $pdfContent);
        
        
        
        $contract=new Contract();
        $contract->staff_id=auth()->user()->id;
        $contract->client_name=$data['consumer_protection_form']['paraOneName'];
        $contract->work=$data['consumer_protection_form']['paraTwoLabourAndMaterialPurpose'] ;
        $contract->contract=$filename;
        $contract->save();
        return response()->json([
            'status' => 'The Contract Url is',
            'url' => url('images/contracts/'. $filename),
        ], 200);
    }
    
    public function staff_generated_contracts(){
        $contracts=Contract::where('staff_id', auth()->user()->id)->orderBy('created_at', 'desc')->get();
        foreach($contracts as $contract){
            $contract->contract=url('images/contracts/'. $contract->contract);
            unset($contract->updated_at);
            unset($contract->staff_id);
        }
         return response()->json([
        'status' => 'The contracts generated by user are as follows',
        'contracts' => $contracts,
    ], 200);
    }
}
